- name: Install Git
  hosts: servers
  vars:
    - packages: ["git"]
  tasks:
    - name: Install "{{item}}" on #{{servers}}
      # debug:
      # msg: {{version}}
      yum:
        name: "{{item}}"
        state: present
      with_items: "{{packages}}"
      become: yes
      become_method: sudo
