---
- hosts: {{hostname}}
  vars:
    - packages: ["git", "nmap"]
  tasks:
    - name: Installing {{packages}} on {{hostname}}
      yum:
        name: {{item}}
        state: present
      with_items: {{packages}}

